name: flutter_lubo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-10.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations: # Add this line
    sdk: flutter

  # 加载图片
  cached_network_image: ^3.1.0
  # 获取网络
  connectivity_plus: ^2.0.2
  # 网络请求
  dio: ^4.0.1
  # 状态管理
  provider: ^6.0.1
  # open url
  url_launcher: ^6.0.12
  # 存储
  shared_preferences: ^2.0.8
  # 吐司
  fluttertoast: ^8.0.8
  flutter_easyloading: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true
